### ISSUE TITLE
Paragraph text gets added to list item

### ISSUE THREAD

**Issue by NYJvanMuijlwijk** [CatHood0/flutter_quill_delta_from_html#14]
When you have a paragraph followed by list (ordered or unordered), the last line of the paragraph gets added to the first list item. Adding an extra <br> prevents this from continuing until its all part of the list, but still results in an unexpected result.

Input
`<p>Start text<br>2nd line</p><ol><li>List item 1</li><li>List item 2</ol><p>Between text<br>Before unordered</p><ul><li>Unordered 1</li><li>Unordered 2</li></ul>`

result
```
Start text
1. 2nd lineList item 1
2. List item 2
Between text
- Before unorderedUnordered 1
- Unordered 2
```

expected
```
Start text
2nd line
1. List item 1
2. List item 2
Between text
Before unordered
- Unordered 1
- Unordered 2
```

**Comment by NYJvanMuijlwijk** [comment]
currently preventing this by inserting an extra <br> at the end of paragraphs with a list after

**Comment by CatHood0** [comment]
I'll check it as soon as possible. Thanks for reporting it!

**Comment by CatHood0** [comment]
@DaemonInc if the issue persists, report it.
