### ISSUE TITLE
Nested Lists

### ISSUE THREAD

**Issue by Nightbl927** [CatHood0/flutter_quill_delta_from_html#5]
Nested list isn't arranged as expected.

```
r"""<ul>
    <li>List item one</li>
    <li>List item two with subitems:
        <ul>
            <li>Subitem 1</li>
            <li>Subitem 2</li>
        </ul>
    </li>
    <li>Final list item</li>
</ul>"""
```

<img width="300" alt="Screenshot 2024-08-04 at 10 01 17 PM" src="https://github.com/user-attachments/assets/f79c96db-c64b-4ab9-a6d0-e040b567e3f1">

**Comment by Nightbl927** [comment]
I was able to figure out that it is caused by a carriage return after `<li>List item two with subitems:`

**Comment by CatHood0** [comment]
I know this could be weird, but, if you divide every tag on different lines, that new lines will be taked, building an unexpected `Delta` with unnecessary lines.

To the parser, the string looks like:
```html
r"""<ul>\n
    <li>List item one</li>\n
    <li>List item two with subitems:\n  <-- these new lines separate the text from the `List` attribute and produce your error
        <ul>\n
            <li>Subitem 1</li>\n
            <li>Subitem 2</li>\n
        </ul>\n
    </li>\n
    <li>Final list item</li>\n
</ul>"""
```

You will need to remove all new lines and create a `HTML` into a only one line.

I test this version without new lines and it works as expected:

```html
<ul><li>List item one </li><li>List item two with subitems: <ul><li>Subitem 1</li><li>Subitem 2</li></ul></li><li>Final list item</li></ul>
```

With that `HTML` this was the `Delta` result (i guess this is the `Delta` that you need)
```dart
Delta()
    ..insert('List item one ')
     ..insert('\n', {'list': 'bullet'})
     ..insert('List item two with subitems: ')
     ..insert('\n', {'list': 'bullet'})
     ..insert('Subitem 1')
     ..insert('\n', {'list': 'bullet', 'indent': 1})
     ..insert('Subitem 2')
     ..insert('\n', {'list': 'bullet', 'indent': 1})
     ..insert('Final list item')
     ..insert('\n', {'list': 'bullet'})
     ..insert('\n');
```

> [!NOTE]
> Sometimes the parser took the leading spaces before append a `HTML` element as normal whitespaces adding unexpected spaces before the text. This issue cannot be fixed because we cannot diff between leading `HTML` element spaces and the spaces into the element.

**Comment by Nightbl927** [comment]
Thank you, CatHood! Your explanation gave me an idea to change the delta insert for listToOp to `delta.insert(node.text!.replaceAll('\n', '').trim());`. I performed some tests and it seems to work on every situation that I could think of. Do you forsee any problems with this solution?
