### ISSUE TITLE
ul li not working well

### ISSUE THREAD

**Issue by AmineLAHRIM** [CatHood0/flutter_quill_delta_from_html#8]
1st bullet point get always skipped and all others come before the text
<img width="704" alt="Screenshot 2024-08-17 at 19 47 11" src="https://github.com/user-attachments/assets/f75c03f7-8c50-441c-b24e-6a48f49304d6">
<img width="874" alt="Screenshot 2024-08-17 at 19 48 02" src="https://github.com/user-attachments/assets/0be4497c-8b26-4f40-a6c1-d0b7d7c08328">
<img width="1081" alt="Screenshot 2024-08-17 at 19 48 21" src="https://github.com/user-attachments/assets/ec21f80a-3b1c-4fab-9131-40c650581b11">

**Comment by Nightbl927** [comment]
Please see #5. We have a discussion on what could causing this.
